services:
  postgres:
    image: postgres:17
    container_name: demo_backend
    restart: always
    environment:
      POSTGRES_USER: demo_backend
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5436:5432"
    volumes:
      - demo_backend_postgres_data:/var/lib/postgresql/data

volumes:
  demo_backend_postgres_data:
